kind: pipeline
type: docker
name: deploy

steps:
- name: notify build start
  image: plugins/webhook
  settings:
    urls: https://api.pushover.net/1/messages.json
    content_type: application/json
    template: |
      {
        "token": "a3arkn5phqihc15auh7ikayxr5yiub",
        "user": "ubb25dk7snjn9hri5137moi3q5k53a",
        "message": "Démarrage du build pour 'apps-dashboard'."
      }

- name: install
  image: node
  commands:
  - npm install

- name: build
  image: node
  commands:
  - npm run-script build

- name: notify build done
  image: plugins/webhook
  settings:
    urls: https://api.pushover.net/1/messages.json
    content_type: application/json
    template: |
      {
        "token": "a3arkn5phqihc15auh7ikayxr5yiub",
        "user": "ubb25dk7snjn9hri5137moi3q5k53a",
        "message": "Mise en production de 'apps-dashboard'."
      }
  when:
    status:
    - success

- name: notify build failed
  image: plugins/webhook
  settings:
    urls: https://api.pushover.net/1/messages.json
    content_type: application/json
    template: |
      {
        "token": "a3arkn5phqihc15auh7ikayxr5yiub",
        "user": "ubb25dk7snjn9hri5137moi3q5k53a",
        "message": "Build de 'apps-dashboard' en erreur."
      }
  when:
    status:
    - failure

- name: cleaning
  image: appleboy/drone-ssh
  settings:
    host: 464i8.ftp.infomaniak.com
    username: 464i8_ci
    port: 22
    key:
      from_secret: SSH_KEY
    script:
      - echo "Cleaning Folder..."
      - cd
      - cd sites/dashboard-apps
      - rm -rf ./*
      - echo "Folder cleaned"
      - exit

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "464i8.ftp.infomaniak.com" ]
    user: 464i8_ci
    key:
      from_secret: SSH_KEY
    recursive: true
    source: ./dist/
    target: ~/sites/dashboard-apps
    script:
      - echo "Done"
      - exit

- name: notify deploy done
  image: plugins/webhook
  settings:
    urls: https://api.pushover.net/1/messages.json
    content_type: application/json
    template: |
      {
        "token": "a3arkn5phqihc15auh7ikayxr5yiub",
        "user": "ubb25dk7snjn9hri5137moi3q5k53a",
        "message": "L'application 'apps-dashboard' a bien été déployée sur l'infrastructure Infomaniak."
      }
  when:
    status:
    - success

- name: notify deploy failed
  image: plugins/webhook
  settings:
    urls: https://api.pushover.net/1/messages.json
    content_type: application/json
    template: |
      {
        "token": "a3arkn5phqihc15auh7ikayxr5yiub",
        "user": "ubb25dk7snjn9hri5137moi3q5k53a",
        "message": "Le déploiement de 'apps-dashboard' sur l'infrastructure Infomaniak a échoué."
      }
  when:
    status:
    - failure

trigger:
  branch:
  - main