---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Apps Princelle"
subtitle: "Dashboard"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false # set false if you want to hide it.

# Optionnal theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "👋 Hello !"
  content: "Here you can access all the applications that I provide. <br /> If you need anything please <a href='https://contact.princelle.org'>contact me</a>."
  # <p>Created and maintained by <a href="https://princelle.org/">Maxime Princelle</a>. If you encounter any bugs with one of these services, please <a href="https://contact.princelle.org">contact me</a>.</p>

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Portfolio"
    icon: "fas fa-book"
    url: "https://princelle.org/"
    target: "_blank"
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/ThePrincelle"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "General"
    icon: "fas fa-cloud"
    items:
      - name: "Mail"
        logo: "assets/tools/mail.svg"
        #subtitle: ""
        tag: "general"
        url: "https://mail.princelle.org"
        target: "_blank"
      - name: "Contacts"
        logo: "assets/tools/contacts.svg"
        #subtitle: ""
        tag: "general"
        url: "https://contacts.princelle.org"
        target: "_blank"
      - name: "Calendar"
        logo: "assets/tools/calendar.svg"
        #subtitle: ""
        tag: "general"
        url: "https://calendar.princelle.org"
        target: "_blank"
  - name: "File Management"
    icon: "fas fa-folder"
    items:
      - name: "Drive"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Personal Drive server based on Nextcloud"
        tag: "file_mgt"
        url: "https://drive.princelle.org"
        target: "_blank"
      - name: "Assets"
        logo: "assets/tools/assets.png"
        subtitle: "Direct access to assets bucket on S3 server"
        tag: "file_mgt"
        url: "https://assets.princelle.org"
        target: "_blank"
      - name: "MinIO (S3 Server)"
        logo: "assets/tools/s3.jpg"
        subtitle: "S3 Server to manage assets"
        tag: "file_mgt"
        url: "https://s3.princelle.org"
        target: "_blank"
      - name: "Cloud (legacy)"
        logo: "assets/tools/cloud.png"
        subtitle: "Old Cloud server, deprecated."
        tag: "file_mgt"
        url: "https://cloud.princelle.org"
        target: "_blank"
  - name: "DevOps"
    icon: "fas fa-code"
    items:
      - name: "Drone CI (GitHub)"
        logo: "assets/tools/droneci.png"
        # subtitle: ""
        tag: "devops"
        url: "https://ci.princelle.org"
        target: "_blank"
      - name: "Drone CI (Git Unistra)"
        logo: "assets/tools/droneci.png"
        # subtitle: "Media requests manager"
        tag: "devops"
        url: "https://drone.princelle.org"
        target: "_blank"
  - name: "Multimédia"
    icon: "fas fa-tv"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Personal Netflix-like service"
        tag: "multimedia"
        url: "https://plex.princelle.org"
        target: "_blank"
      - name: "Overseerr"
        logo: "assets/tools/overseerr.png"
        subtitle: "Media requests manager"
        tag: "multimedia"
        url: "https://overseerr.princelle.org"
        target: "_blank"
  - name: "AdminSys"
    icon: "fas fa-server"
    items:
      - name: "Cockpit"
        logo: "assets/tools/debian.png"
        subtitle: "System monitoring"
        tag: "adminsys"
        url: "https://servers.princelle.org"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker monitoring"
        tag: "devops"
        url: "https://portainer.princelle.org"
        target: "_blank"
      - name: "Tautulli"
        logo: "assets/tools/tautulli.png"
        subtitle: "Plex server monitoring"
        tag: "media-mgt"
        url: "https://tautulli.princelle.org"
        target: "_blank"
  - name: "Reverse Proxys"
    icon: "fas fa-compass"
    items:
      - name: "Cloud Network"
        logo: "assets/tools/nginx.png"
        # subtitle: ""
        tag: "reverse-proxy"
        url: "https://proxy.cloud.princelle.org"
        target: "_blank"
      - name: "Dalton Network"
        logo: "assets/tools/nginx.png"
        # subtitle: ""
        tag: "reverse-proxy"
        url: "https://proxy.dalton.princelle.org"
        target: "_blank"
  - name: "Multimedia Management"
    icon: "fas fa-download"
    items:
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Movie fetch manager"
        tag: "media-mgt"
        url: "https://radarr.princelle.org"
        target: "_blank"
      - name: "Sonarr (English)"
        logo: "assets/tools/sonarr.png"
        subtitle: "TV Shows (English) fetch manager"
        tag: "media-mgt"
        url: "https://sonarr-en.princelle.org"
        target: "_blank"
      - name: "Sonarr (French)"
        logo: "assets/tools/sonarr.png"
        subtitle: "TV Shows (French) fetch manager"
        tag: "media-mgt"
        url: "https://sonarr-fr.princelle.org"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.png"
        subtitle: "Music fetch manager"
        tag: "media-mgt"
        url: "https://lidarr.princelle.org"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        subtitle: "Torrent source management"
        tag: "media-mgt"
        url: "https://prowlarr.princelle.org"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        subtitle: "Torrent downloader"
        tag: "media-mgt"
        url: "https://downloads.princelle.org"
        target: "_blank"
      
